logging:
  level:
    com.oak.gateway: debug

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order-service/** # 匹配相应路径规则
          filters:
            - StripPrefix=2 # 表示请求时将会忽略2位路径path
            - name: RateLimiter
              args:
                #key-resolver: '#{@uriKeyResolver}' # 按照地址进行限流, 用于限流的键的解析器Bean对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象
                redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 5 # 令牌桶总容量
      defaultFilters:
        - name: Hystrix # Hystrix Filter的名称、设置成默认的
          args:
            name: orderFallbackHystrixCommand # HystrixCommand 的名字, 关联设置熔断超时时间中的名称
            fallbackUri: forward:/fallback # fallback对用的uri
        - name: Logging

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    #主机名称
    hostname: ${spring.cloud.client.ip-address}
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    preferIpAddress: true
    instance_id: ${spring.cloud.client.ip-address}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    orderFallbackHystrixCommand: # 设置某个服务的熔断超时时间限制
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
server:
  port: 80